/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTrashRouteImport } from './routes/_authenticated/trash'
import { Route as AuthenticatedScanRouteImport } from './routes/_authenticated/scan'
import { Route as AuthenticatedSameFolderRouteImport } from './routes/_authenticated/same-folder'
import { Route as AuthenticatedResultsRouteImport } from './routes/_authenticated/results'
import { Route as AuthenticatedOldFilesRouteImport } from './routes/_authenticated/old-files'
import { Route as AuthenticatedLargeFilesRouteImport } from './routes/_authenticated/large-files'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTrashRoute = AuthenticatedTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedScanRoute = AuthenticatedScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSameFolderRoute = AuthenticatedSameFolderRouteImport.update({
  id: '/same-folder',
  path: '/same-folder',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedResultsRoute = AuthenticatedResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOldFilesRoute = AuthenticatedOldFilesRouteImport.update({
  id: '/old-files',
  path: '/old-files',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLargeFilesRoute = AuthenticatedLargeFilesRouteImport.update({
  id: '/large-files',
  path: '/large-files',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/large-files': typeof AuthenticatedLargeFilesRoute
  '/old-files': typeof AuthenticatedOldFilesRoute
  '/results': typeof AuthenticatedResultsRoute
  '/same-folder': typeof AuthenticatedSameFolderRoute
  '/scan': typeof AuthenticatedScanRoute
  '/trash': typeof AuthenticatedTrashRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/large-files': typeof AuthenticatedLargeFilesRoute
  '/old-files': typeof AuthenticatedOldFilesRoute
  '/results': typeof AuthenticatedResultsRoute
  '/same-folder': typeof AuthenticatedSameFolderRoute
  '/scan': typeof AuthenticatedScanRoute
  '/trash': typeof AuthenticatedTrashRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/large-files': typeof AuthenticatedLargeFilesRoute
  '/_authenticated/old-files': typeof AuthenticatedOldFilesRoute
  '/_authenticated/results': typeof AuthenticatedResultsRoute
  '/_authenticated/same-folder': typeof AuthenticatedSameFolderRoute
  '/_authenticated/scan': typeof AuthenticatedScanRoute
  '/_authenticated/trash': typeof AuthenticatedTrashRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/large-files'
    | '/old-files'
    | '/results'
    | '/same-folder'
    | '/scan'
    | '/trash'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/large-files'
    | '/old-files'
    | '/results'
    | '/same-folder'
    | '/scan'
    | '/trash'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/dashboard'
    | '/_authenticated/large-files'
    | '/_authenticated/old-files'
    | '/_authenticated/results'
    | '/_authenticated/same-folder'
    | '/_authenticated/scan'
    | '/_authenticated/trash'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/trash': {
      id: '/_authenticated/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof AuthenticatedTrashRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/scan': {
      id: '/_authenticated/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof AuthenticatedScanRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/same-folder': {
      id: '/_authenticated/same-folder'
      path: '/same-folder'
      fullPath: '/same-folder'
      preLoaderRoute: typeof AuthenticatedSameFolderRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/results': {
      id: '/_authenticated/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof AuthenticatedResultsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/old-files': {
      id: '/_authenticated/old-files'
      path: '/old-files'
      fullPath: '/old-files'
      preLoaderRoute: typeof AuthenticatedOldFilesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/large-files': {
      id: '/_authenticated/large-files'
      path: '/large-files'
      fullPath: '/large-files'
      preLoaderRoute: typeof AuthenticatedLargeFilesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLargeFilesRoute: typeof AuthenticatedLargeFilesRoute
  AuthenticatedOldFilesRoute: typeof AuthenticatedOldFilesRoute
  AuthenticatedResultsRoute: typeof AuthenticatedResultsRoute
  AuthenticatedSameFolderRoute: typeof AuthenticatedSameFolderRoute
  AuthenticatedScanRoute: typeof AuthenticatedScanRoute
  AuthenticatedTrashRoute: typeof AuthenticatedTrashRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLargeFilesRoute: AuthenticatedLargeFilesRoute,
  AuthenticatedOldFilesRoute: AuthenticatedOldFilesRoute,
  AuthenticatedResultsRoute: AuthenticatedResultsRoute,
  AuthenticatedSameFolderRoute: AuthenticatedSameFolderRoute,
  AuthenticatedScanRoute: AuthenticatedScanRoute,
  AuthenticatedTrashRoute: AuthenticatedTrashRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
