/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrashRouteImport } from './routes/trash'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as SameFolderRouteImport } from './routes/same-folder'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as OldFilesRouteImport } from './routes/old-files'
import { Route as LargeFilesRouteImport } from './routes/large-files'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'

const TrashRoute = TrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const SameFolderRoute = SameFolderRouteImport.update({
  id: '/same-folder',
  path: '/same-folder',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const OldFilesRoute = OldFilesRouteImport.update({
  id: '/old-files',
  path: '/old-files',
  getParentRoute: () => rootRouteImport,
} as any)
const LargeFilesRoute = LargeFilesRouteImport.update({
  id: '/large-files',
  path: '/large-files',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/large-files': typeof LargeFilesRoute
  '/old-files': typeof OldFilesRoute
  '/results': typeof ResultsRoute
  '/same-folder': typeof SameFolderRoute
  '/scan': typeof ScanRoute
  '/trash': typeof TrashRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/large-files': typeof LargeFilesRoute
  '/old-files': typeof OldFilesRoute
  '/results': typeof ResultsRoute
  '/same-folder': typeof SameFolderRoute
  '/scan': typeof ScanRoute
  '/trash': typeof TrashRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/large-files': typeof LargeFilesRoute
  '/old-files': typeof OldFilesRoute
  '/results': typeof ResultsRoute
  '/same-folder': typeof SameFolderRoute
  '/scan': typeof ScanRoute
  '/trash': typeof TrashRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/large-files'
    | '/old-files'
    | '/results'
    | '/same-folder'
    | '/scan'
    | '/trash'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/large-files'
    | '/old-files'
    | '/results'
    | '/same-folder'
    | '/scan'
    | '/trash'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/large-files'
    | '/old-files'
    | '/results'
    | '/same-folder'
    | '/scan'
    | '/trash'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LargeFilesRoute: typeof LargeFilesRoute
  OldFilesRoute: typeof OldFilesRoute
  ResultsRoute: typeof ResultsRoute
  SameFolderRoute: typeof SameFolderRoute
  ScanRoute: typeof ScanRoute
  TrashRoute: typeof TrashRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trash': {
      id: '/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof TrashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/same-folder': {
      id: '/same-folder'
      path: '/same-folder'
      fullPath: '/same-folder'
      preLoaderRoute: typeof SameFolderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/old-files': {
      id: '/old-files'
      path: '/old-files'
      fullPath: '/old-files'
      preLoaderRoute: typeof OldFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/large-files': {
      id: '/large-files'
      path: '/large-files'
      fullPath: '/large-files'
      preLoaderRoute: typeof LargeFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LargeFilesRoute: LargeFilesRoute,
  OldFilesRoute: OldFilesRoute,
  ResultsRoute: ResultsRoute,
  SameFolderRoute: SameFolderRoute,
  ScanRoute: ScanRoute,
  TrashRoute: TrashRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
